name: take_home_challenge_innoscripta
description: Innoscripta Take Home Challenge
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # To Store Data In Local Storage
  shared_preferences: ^2.2.2

  # Make Pages Responsive To All Devices
  flutter_screenutil: ^5.9.0

  # For Localization
  intl: ^0.18.1

  # Handle Success/Error State From Data Source
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^7.6.4

  # Loader
  flutter_spinkit: ^5.2.0

  # Being able to compare objects in Dart
  equatable: ^2.0.5

  # Fetch Data From Api
  dio: ^5.4.0

  # Logging Interceptor
  logging: ^1.2.0

  # BloC State Management
  flutter_bloc: ^8.1.3

  # Json Annotation
  json_annotation: ^4.8.1

  # Code generation
  freezed: ^2.4.5

  google_fonts: 6.1.0

  uuid: ^4.2.2

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  # To generate Localization File's
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  # Localization config
#  flutter_localizations:
#    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

